server:
  port: 8101

spring:
  application:
    name: yf-exam
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
   # url: jdbc:mysql://localhost:3306/zs_exam?characterEncoding=UTF-8&useUnicode=true&useSSL=false
    url: jdbc:mysql://localhost:3306/zs_exam?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Sd!4888202
   # password: Root@123456

  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000

# 日志级别
logging:
  level:
    root: debug
